name: 'Auto Release Draft'
description: 'Drafts a GitHub release with the changes introduced by newly created version tag.'
author: 'Steven Araujo'
outputs:
  release-url:
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'node16'
  main: 'dist/index.js'
